package de.corneliusmay.silkspawners.wiring.processor;

import de.corneliusmay.silkspawners.wiring.Loader;
import java.io.IOException;
import java.io.Writer;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;
import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.Diagnostic;

class RegistryGenerator {

    private static final String TEMPLATE = """
            package %s;

            import %s;
            import java.util.List;
            import java.util.Map;
            import java.util.function.Function;

            // Generated by %s
            @SuppressWarnings("unchecked")
            final class WiredComponents {

                static final List<Class<? extends Loader>> LOAD_ORDER = List.of(
            %s);

                static final Map<Class<?>, List<Class<?>>> PARAMETERS = Map.ofEntries(
            %s);

                static final Map<Class<?>, Function<Object[], Object>> FACTORIES = Map.ofEntries(
            %s);

                static final Map<Class<?>, Class<? extends Loader>> PRODUCT_OWNERS = Map.ofEntries(
            %s);

                static final Map<Class<?>, Function<Loader, Object>> PRODUCT_GETTERS = Map.ofEntries(
            %s);

                private WiredComponents() {}
            }
            """;

    private final WiringModel model;

    private final String registryPackage;

    RegistryGenerator(WiringModel model, String registryPackage) {
        this.model = model;
        this.registryPackage = registryPackage;
    }

    void write(ProcessingEnvironment processingEnv) {
        try (Writer writer = processingEnv
                .getFiler()
                .createSourceFile(registryPackage + ".WiredComponents")
                .openWriter()) {
            writer.write(render());
        } catch (IOException ex) {
            processingEnv
                    .getMessager()
                    .printMessage(Diagnostic.Kind.ERROR, "Failed to generate component registry: " + ex.getMessage());
        }
    }

    private String render() {
        return TEMPLATE.formatted(
                registryPackage,
                Loader.class.getName(),
                WiredProcessor.class.getName(),
                loadOrderEntries(),
                parameterEntries(),
                factoryEntries(),
                productOwnerEntries(),
                productGetterEntries());
    }

    private String loadOrderEntries() {
        return block(model.loadOrder().stream().map(loader -> loader + ".class"));
    }

    private String parameterEntries() {
        return block(model.components().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, List.of(%s))"
                        .formatted(
                                entry.getKey(),
                                entry.getValue().parameters().stream()
                                        .map(parameter -> parameter.erasedClass() + ".class")
                                        .collect(Collectors.joining(", ")))));
    }

    private String factoryEntries() {
        return block(model.components().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, arguments -> new %s(%s))"
                        .formatted(
                                entry.getKey(),
                                entry.getKey(),
                                factoryArguments(entry.getValue().parameters()))));
    }

    private String factoryArguments(List<WiringModel.Parameter> parameters) {
        return IntStream.range(0, parameters.size())
                .mapToObj(index ->
                        "(%s) arguments[%d]".formatted(parameters.get(index).declaredType(), index))
                .collect(Collectors.joining(", "));
    }

    private String productOwnerEntries() {
        return block(model.products().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, %s.class)"
                        .formatted(entry.getKey(), entry.getValue().owner())));
    }

    private String productGetterEntries() {
        return block(model.products().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, loader -> ((%s) loader).%s())"
                        .formatted(
                                entry.getKey(),
                                entry.getValue().owner(),
                                entry.getValue().getter())));
    }

    private String block(Stream<String> entries) {
        return entries.collect(Collectors.joining(",\n")).indent(8).stripTrailing();
    }
}
