name: Build

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: ${{ github.event_name == 'push' && 'generate-and-submit' || 'disabled' }}

      - run: ./gradlew assemble --no-daemon --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          path: |
            build/libs/SilkSpawners_v2.jar
            build/libs/SilkSpawners_v2-api-*.jar
