name: Crowdin

on:
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crowdin/github-action@v2
        with:
          translation: "Plugin/src/main/resources/locales/messages_%two_letters_code%.properties"
          source: "Plugin/src/main/resources/locales/messages_en.properties"
          upload_sources: true
          upload_translations: true
          download_sources: false
          download_translations: true
          create_pull_request: false
          commit_message: "chore(locales): new crowdin translations"
          localization_branch_name: master
          push_translations: true
          export_only_approved: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
