name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get plugin version
        id: yaml-data
        uses: KJ002/read-yaml@1.6
        with:
          file: '${{ github.workspace }}/Plugin/src/main/resources/plugin.yml'
          key-path: '["version"]'
      - name: Store version
        uses: "finnp/create-file-action@1.0.0"
        env:
          FILE_NAME: "version.html"
          FILE_DATA: "${{ steps.yaml-data.outputs.data }}"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: 'Set up GCoogle Cloud Envoirement'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.6.0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Deploy'
        uses: 'google-github-actions/upload-cloud-storage@v0.6.0'
        with:
          path: '/home/runner/work/SilkSpawners_v2/SilkSpawners_v2/target/SilkSpawners_v2.jar'
          destination: '${{ secrets.GCS_BUCKET }}/${{ steps.yaml-data.outputs.data }}'
      - name: 'Update version'
        uses: 'google-github-actions/upload-cloud-storage@v0.6.0'
        with:
          path: 'version.html'
          destination: '${{ secrets.GCS_BUCKET }}'



