name: Publish

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest

    env:
      HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
      HANGAR_ID: ${{ secrets.HANGAR_ID }}
      HANGAR_PUB_CHANNEL: ${{ secrets.HANGAR_PUB_CHANNEL }}
      HANGAR_PLATFORM_VERSIONS: ${{ secrets.HANGAR_PLATFORM_VERSIONS }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew :Publication:publishPluginPublicationToHangar
