name: Publish

on:
  release:
    types: [ published ]
  workflow_call:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
          filter: tree:0

      - id: beta
        run: echo "version=$(git describe --tags --long --exclude 'api-*' | sed -E 's/^v//; s/-([0-9]+)-g([0-9a-f]+)$/-beta.\1+\2/')" >> $GITHUB_OUTPUT

      - uses: actions/setup-java@v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v6

      - name: Publish to Hangar
        run: ./gradlew :Publication:publishPluginPublicationToHangar --no-daemon --stacktrace
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          HANGAR_ID: ${{ secrets.HANGAR_ID }}
          PUBLISH_VERSIONS: ${{ vars.PUBLISH_VERSIONS }}
          HANGAR_PUBLISH_CHANNEL: ${{ (github.event_name == 'workflow_dispatch' || github.event.release.prerelease) && 'Preview' || 'Release' }}
          PUBLISH_BETA_VERSION: ${{ steps.beta.outputs.version }}

      - name: Publish to Modrinth
        run: ./gradlew :Publication:modrinth --no-daemon --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_ID: ${{ secrets.MODRINTH_ID }}
          PUBLISH_VERSIONS: ${{ vars.PUBLISH_VERSIONS }}
          MODRINTH_PUBLISH_CHANNEL: ${{ (github.event_name == 'workflow_dispatch' || github.event.release.prerelease) && 'beta' || 'release' }}
          PUBLISH_BETA_VERSION: ${{ steps.beta.outputs.version }}
