name: Release

on:
  push:
    tags:
      - '*'
      - '!api-*'
  workflow_call:
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    outputs:
      already-published: ${{ steps.existing.outputs.published }}
      draft: ${{ steps.state.outputs.draft }}

    steps:

      # https://github.com/actions/checkout/issues/1471
      - uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/download-artifact@v8
        with:
          name: artifact
          path: artifact

      - id: tag
        run: echo "latest=$(git describe --tags --abbrev=0 --exclude 'api-*')" >> $GITHUB_OUTPUT

      - id: existing
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo "published=$(gh release view '${{ steps.tag.outputs.latest }}' --json isDraft --jq '.isDraft == false' 2> /dev/null || echo false)" >> $GITHUB_OUTPUT

      - id: changes
        run: |
          {
            echo 'changes<<CHANGES_EOF'
            git log --oneline $(git tag -l 'v[0-9]*' --format='%(objectname)' --sort=creatordate | tail -n2 | head -n1)..HEAD --pretty=format:%s | grep -E '(^feat)|(^fix)' || true
            echo CHANGES_EOF
          } >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v3
        with:
          draft: ${{ github.event_name == 'workflow_dispatch' }}
          name: ${{ steps.tag.outputs.latest }}
          tag_name: ${{ steps.tag.outputs.latest }}
          body: ${{ steps.changes.outputs.changes }}
          append_body: ${{ steps.existing.outputs.published == 'true' }}
          files: artifact/*

      - id: state
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo "draft=$(gh release view '${{ steps.tag.outputs.latest }}' --json isDraft --jq .isDraft)" >> $GITHUB_OUTPUT

  publish:
    if: github.event_name == 'push' && needs.release.outputs.already-published != 'true' && needs.release.outputs.draft == 'false'
    needs: release
    uses: ./.github/workflows/publish.yml
    secrets: inherit
