name: Release

on:
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:

      # https://github.com/actions/checkout/issues/1471
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          
      - uses: actions/download-artifact@v4

      - id: tag
        run: echo "latest=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.tag.outputs.latest }}

      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: ${{ steps.tag.outputs.latest }}
          tag_name: ${{ steps.tag.outputs.latest }}
          files: artifact/*