name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@1.6      
        with:
          file: '${{ github.workspace }}/Plugin/src/main/resources/plugin.yml'          
          key-path: '["version"]' 
      
      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
      
      #- name: 'Set up GCoogle Cloud Envoirement'
       # uses: 'google-github-actions/auth@v0.6.0'
        #with:
       #   credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      #- name: 'Set up Cloud SDK'
       # uses: 'google-github-actions/setup-gcloud@v0.6.0'
      #- name: 'Use gcloud CLI'
       # run: 'gcloud info'
      #- name: 'Deploy'
       # uses: 'google-github-actions/upload-cloud-storage@v0.6.0'
        #with:
         # path: '/home/runner/work/SilkSpawners_v2/SilkSpawners_v2/target/SilkSpawners_v2.jar'
          #destination: '${{ secrets.GCS_BUCKET }}'
